### ISSUE TITLE
Don't see the sum of my portfolio

### ISSUE THREAD

**Issue by Mandy2000** [pgrimaud/lametric-bitpanda#2]
Hi Pierre,
when I start your app on my LaMetric I only see the value of my FIRST asset. I want to see the total of my Bitpanda portfolio. It doesn't matter which setting I choose I just see the SUM OF MY FIRST ASSET (in my case BTC). 
The icon is the green Bitpanda logo but the value just my BTC asset. If I change the setting the icon changes to BTC but the value stays the same (in that case the correct value of my BTC asset. 
How can I see the TOTAL AMOUNT of my portfolio?

thanks for help

**Comment by Mandy2000** [comment]
Should mean SUM not sun ☀️😋

**Comment by pgrimaud** [comment]
Hey, I just fixed this issue. Could you try on your LaMetric? 

Thanks :)
